test workflow without signing

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,9 +1,18 @@
 name: Build and Release Void Linux Packages
 
+env:
+  TAG: workflow-${{ github.run_number }}
+
 on:
   push:
-    tags:
-      - "*"
+    branches:
+      - main
+    paths:
+      - srcpkgs/**
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 
 jobs:
   build:
@@ -14,59 +23,113 @@ jobs:
     runs-on: ubuntu-latest
     env:
       XBPS_ALLOW_RESTRICTED: "yes"
-      XBPS_PASSPHRASE: ${{ secrets.SIGN_PASS }}
+      # XBPS_PASSPHRASE: ${{ secrets.SIGN_PASS }}
       XBPS_TARGET_ARCH: ${{ matrix.arch }}
       REPO_OWNER: "${{ github.repository_owner }}"
       REPO_NAME: "${{ github.event.repository.name }}"
+      PATH: "/opt/xbps/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
 
     steps:
-      - name: checkout ${{ env.REPO_NAME }}
-        uses: actions/checkout@v4
-        with:
-          ref: main
-          path: ${{ env.REPO_NAME }}
+      - name: More free space
+        run: |
+          sudo rm --recursive --force /usr/local/lib/android /usr/share/dotnet /opt/ghc /usr/local/.ghcup /opt/hostedtoolcache/CodeQL
+
+      - name: prepare xbps-static
+        run: |
+          mkdir -p /opt/xbps
+          curl --fail -sL http://repo-default.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz \
+          | tar -xJf - -C /opt/xbps
 
       - name: checkout void-packages
         uses: actions/checkout@v4
         with:
           repository: void-linux/void-packages
           ref: master
-          path: void-packages
+          # path: void-packages
 
-      - name: copy
+      - name: Merge this repository
+        working-directory: ${{ github.workspace }}
         run: |
-          cp -rv ${{ env.REPO_NAME }}/srcpkgs/* void-packages/srcpkgs
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+          git remote add -f grvn https://github.com/grvn/void-packages.git
+          git merge --no-commit --strategy-option=theirs --allow-unrelated-histories -Xignore-space-change grvn/main
+          mkdir -p hostdir/binpkgs
+          gh release download --pattern "*${{ matrix.arch }}*" --dir hostdir/binpkgs || true
+          if [[ ${{ matrix.arch }} == x86_64 ]]; then
+            rm --force hostdir/binpkgs/*x86_64-musl*
+          fi
 
-      - name: prepare xbps-static
+      - name: Identify changes to build
+        working-directory: ${{ github.workspace }}
         run: |
-          mkdir -p /opt/xbps
-          url --fail -sL http://repo-default.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz \
-          | tar -xJf - -C /opt/xbps
+          latest_name=$(gh release view --json tagName --jq '.tagName' || echo "Initial Commit")
+          latest_sha=$(git rev-list --max-count=1 ${latest_name} 2>/dev/null || git rev-list --max-parents=0 grvn/main)
+          echo "Latest Tag Name: ${latest_name}"
+          echo "Latest Tag SHA: ${latest_sha}"
 
-      - name: set path
-        run: |
-          echo "/opt/xbps/usr/bin/" >> ${GITHUB_PATH}
+          git diff-tree -r --no-renames --name-only --diff-filter=AM ${latest_sha} ${{ github.sha }} -- 'srcpkgs/**' \
+          | cut -d/ -f 2 | xargs ./xbps-src sort-dependencies | tee /tmp/templates
 
       - name: setup binary bootstrap
-        working-directory: void-packages
+        working-directory: ${{ github.workspace }}
         run: |
           ./xbps-src -m masterdir-${{ matrix.arch }} -A ${{ matrix.arch }} binary-bootstrap
 
       # -------------------- Packages to build --------------------
 
-      - name: build rebos
-        working-directory: void-packages
+      - name: build pkgs
+        working-directory: ${{ github.workspace }}
         run: |
-          ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} rebos
+          pkgs=$(cat /tmp/templates)
+          for pkg in ${pkgs}; do
+            ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} "${pkg}" || printf "Failed building ${pkg}!\n"
+          done
 
       # -----------------------------------------------------------
 
+      - name: Cleanup
+        working-directory: ${{ github.workspace }}/hostdir/binpkgs
+        run: |
+          xbps-rindex --clean ${PWD}
+          xbps-rindex --remove-obsoletes ${PWD}
+
+      # - name: sign
+      #   working-directory: ${{ github.workspace }}/hostdir/binpkgs
+      #   run: |
+      #     echo "${{ secrets.PRIV_KEY }}" > private.pem
+      #     xbps-rindex --privkey private.pem --sign --signedby "${{ env.REPO_NAME }}-github-actions" ${PWD}
+      #     xbps-rindex --privkey private.pem --sign-pkg *.xbps
+      #     rm privkey.pem
+
+      - name: checksum
+        working-directory: ${{ github.workspace }}/hostdir/binpkgs
+        run: |
+          for file in *.xbps; do
+            sha256sum "${file}" | cut -d ' ' -f 1 > "${file}.sha256sum"
+            sha512sum "${file}" | cut -d ' ' -f 1 > "${file}.sha512sum"
+          done
+
+      - name: Upload Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ matrix.arch }}-repodata
+          path: ${{ github.workspace }}/hostdir/binpkgs
+
+      - name: short sha
+        working-directory: ${{ github.workspace }}
+        run: |
+          printf "SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
+
       - name: release
+        working-directory: ${{ github.workspace }}/hostdir/binpkgs
         uses: softprops/action-gh-release@v1
         with:
+          name: ${{ env.SHORT_SHA }}
+          tag_name: ${{ env.TAG }}
           files: |
-            void-packages/hostdir/binpkgs/*.xbps
-            void-packages/hostdir/binpkgs/*.sha256sum
-            void-packages/hostdir/binpkgs/*.sha512sum
-            void-packages/hostdir/binpkgs/*.sig2
-            void-packages/hostdir/binpkgs/*repodata
+            *.xbps
+            *.sha256sum
+            *.sha512sum
+            *.sig2
+            *repodata
