update workflows with more logic

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,6 +2,7 @@ name: Build and Release Void Linux Packages
 
 env:
   TAG: workflow-${{ github.run_number }}
+  SHA: ${{ github.sha }}
 
 on:
   workflow_dispatch:
@@ -27,6 +28,7 @@ jobs:
     runs-on: ubuntu-22.04
     if: ${{ github.ref == 'refs/heads/main' }}
     env:
+      ARCH: ${{ matrix.arch }}
       XBPS_ALLOW_RESTRICTED: "yes"
       XBPS_TARGET_ARCH: ${{ matrix.arch }}
       REPO_OWNER: "${{ github.repository_owner }}"
@@ -58,21 +60,21 @@ jobs:
           git remote add -f grvn https://github.com/grvn/void-packages.git
           git merge --no-commit --strategy-option=theirs --allow-unrelated-histories -Xignore-space-change grvn/main
           mkdir -p hostdir/binpkgs
-          gh release download --pattern "*${{ matrix.arch }}*" --dir hostdir/binpkgs || true
-          if [[ ${{ matrix.arch }} == x86_64 ]]; then
+          gh release download --pattern "*${ARCH}*" --dir hostdir/binpkgs --repo grvn/void-packages || true
+          if [[ $ARCH == x86_64 ]]; then
             rm --force hostdir/binpkgs/*x86_64-musl*
           fi
 
       - name: Identify changes to build
         working-directory: ${{ github.workspace }}
         run: |
-          latest_name=$(gh release view --json tagName --jq '.tagName' || echo "Initial Commit")
+          latest_name=$(gh release view --json tagName --jq '.tagName' --repo grvn/void-packages || echo "Initial Commit")
           latest_sha=$(git rev-list --max-count=1 ${latest_name} 2>/dev/null || git rev-list --max-parents=0 grvn/main)
           echo "Latest Tag Name: ${latest_name}"
           echo "Latest Tag SHA: ${latest_sha}"
 
-          git diff-tree -r --no-renames --name-only --diff-filter=AM ${latest_sha} ${{ github.sha }} -- 'srcpkgs/**' \
-          | cut -d/ -f 2 | xargs ./xbps-src sort-dependencies | tee /tmp/templates
+          git diff-tree -r --no-renames --name-only --diff-filter=AM ${latest_sha} ${SHA} -- 'srcpkgs/**' \
+          | cut -d/ -f 2 | uniq | xargs ./xbps-src sort-dependencies | tee /tmp/templates
 
       - name: setup binary bootstrap
         working-directory: ${{ github.workspace }}
@@ -86,7 +88,7 @@ jobs:
         run: |
           pkgs=$(cat /tmp/templates)
           for pkg in ${pkgs}; do
-            ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} "${pkg}" || printf "Failed building ${pkg}!\n"
+            ./xbps-src pkg -j$(nproc) -m masterdir-${ARCH} "${pkg}" || printf "Failed building ${pkg}!\n"
           done
 
       # -----------------------------------------------------------
@@ -104,7 +106,7 @@ jobs:
           XBPS_PASSPHRASE: ${{ secrets.SIGN_PASS }}
         run: |
           printf "%s\n" "${PRIVKEY}" > key.pem
-          xbps-rindex --privkey key.pem --sign --signedby "${{ env.REPO_NAME }}-github-actions" ${PWD}
+          xbps-rindex --privkey key.pem --sign --signedby "${REPO_NAME}-github-actions" ${PWD}
           xbps-rindex --privkey key.pem --sign-pkg ${PWD}/*.xbps
           rm -f key.pem
 
@@ -125,7 +127,7 @@ jobs:
       - name: short sha
         working-directory: ${{ github.workspace }}
         run: |
-          printf "SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
+          printf "SHORT_SHA=$(git rev-parse --short ${SHA})" >> $GITHUB_ENV
 
       - name: release
         uses: softprops/action-gh-release@v2
